server:
  port: 9999
spring:
  application:
    name: rilsy
  datasource:
    # 多数据配置
    dynamic:
      primary: system
      datasource:
        # 系统数据库
        system:
          url: jdbc:mysql://42.193.218.79:13658/hcums?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: Zbx.33578
          driver-class-name: com.mysql.cj.jdbc.Driver
        # 联思数据库
        imes:
          url: jdbc:sqlserver://172.16.30.254:1433;database=IMES_royal
          username: zbx
          password: abc.123
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
# SaToken 权限认证配置
sa-token:
  token-name: token
  is-concurrent: false
  token-style: simple-uuid
  is-log: false
logging:
  level:
    com.zbx.rilsy.system.dao.CaptchaDao: debug
